New: added priyankar pal
Design-and-Code/Opensource-practice pull request #48
Opened 2023-02-17 15:25 UTC by priyankarpal

Added my name. 

![image](https://user-images.githubusercontent.com/88102392/219695197-2808c919-445a-4b14-972f-30c9a5b64a50.png)

2023-02-17 16:56 UTC, Panquesito7 requested changes
Please revert the other changes and keep your profile additions only.
Let us know if you need any help with doing that. Thanks. 🙂

2023-02-17 17:53 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-23 03:40 UTC, mahfuztbt approved these changes

2023-02-23 15:53 UTC, Panquesito7 approved these changes

2023-02-26 20:23 UTC, SurajPratap10 approved these changes

2023-02-27 04:14 UTC, Panquesito7 requested changes
Please resolve the merge conflicts [**here**](https://github.com/Design-and-Code/Opensource-practice/pull/48/conflicts). If you need any help, you can ask for help here or on our [**Discord server**](https://discord.gg/gM3bG4rAU5). You can also check the [GitHub Docs](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-on-github) to make the process easier. 🙂

2023-02-27 12:49 UTC, SurajPratap10 approved these changes
looks good now

2023-02-27 18:11 UTC, Panquesito7 commented on README.md
> +
```suggestion
```

2023-02-27 18:22 UTC, Panquesito7 approved these changes
Thanks! 🎉

2023-02-27 18:22 UTC, merged